apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: movie-store-api-hpa
  namespace: movie-store
  labels:
    app: movie-store-api
    component: api
    app.kubernetes.io/name: movie-store-api-hpa
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: movie-store-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-store-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: movie-store-processor-hpa
  namespace: movie-store
  labels:
    app: movie-store-processor
    component: data-processor
    app.kubernetes.io/name: movie-store-processor-hpa
    app.kubernetes.io/component: data-processor
    app.kubernetes.io/part-of: movie-store-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-store-processor
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Longer stabilization for data processing
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60