# External Secrets Operator configuration for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: movie-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
# External Secret for database credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: movie-store
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: database-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_HOST
    remoteRef:
      key: "movie-store/dev/database-v2"
      property: host
  - secretKey: DB_NAME
    remoteRef:
      key: "movie-store/dev/database-v2"
      property: dbname
  - secretKey: DB_USER
    remoteRef:
      key: "movie-store/dev/database-v2"
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "movie-store/dev/database-v2"
      property: password

---
# External Secret for Redis credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: movie-store
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
  - secretKey: REDIS_HOST
    remoteRef:
      key: "movie-store/dev/redis-v2"
      property: host

# Elasticsearch removed - using PostgreSQL for all queries