apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service
  namespace: movie-store
  annotations:
    eks.amazonaws.com/role-arn: "REPLACE_WITH_IAM_ROLE_ARN"
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: movie-store-platform

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-processor
  namespace: movie-store
  annotations:
    eks.amazonaws.com/role-arn: "REPLACE_WITH_IAM_ROLE_ARN"
  labels:
    app.kubernetes.io/name: data-processor
    app.kubernetes.io/part-of: movie-store-platform